name:                midterm2022
version:             0.1.0.0
github:              "githubuser/midterm2022"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
  - README.md
  - CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/midterm2022#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  midterm2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - midterm2022
      - containers

tests:
  midterm2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - midterm2022
      - containers
      - hspec